version: "3.8"

services:

  # Services

  service1:
    image: node:14.17.5
    working_dir: /app
    command: [ "npm", "run", "start:dev" ]
    network_mode: host
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ./service1:/app:z

  service2:
    image: node:14.17.5
    working_dir: /app
    command: [ "npm", "run", "start:dev" ]
    network_mode: host
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ./service2:/app:z

  # Infrastructure

  api-gateway:
    image: revomatico/docker-kong-oidc:2.5.1-1
    volumes:
      - ./kong.yml:/usr/local/kong/declarative/kong.yml:z
    network_mode: host
    user: root
    environment:
      KONG_LOG_LEVEL: 'debug'
      KONG_PROXY_LISTEN: '0.0.0.0:80, 0.0.0.0:8443 ssl http2'
      KONG_ADMIN_LISTEN: '0.0.0.0:7001, 0.0.0.0:7444 ssl'
      KONG_STATUS_LISTEN: '0.0.0.0:7100'
      KONG_DATABASE: 'off'
      KONG_NGINX_WORKER_PROCESSES: '1'
      KONG_ADMIN_ACCESS_LOG: '/dev/stdout'
      KONG_ADMIN_ERROR_LOG: '/dev/stdout'
      KONG_PROXY_ERROR_LOG: '/dev/stdout'
      KONG_X_SESSION_STORAGE: 'cookie'
      # KONG_PLUGINS: 'bundled,oidc'
      KONG_DECLARATIVE_CONFIG: '/usr/local/kong/declarative/kong.yml'
  # redis:
  #   image: redis:6.2.5
  #   ports:
  #     - target: 6379
  #       published: 6379

  # redis-commander:
  #   image: rediscommander/redis-commander:latest
  #   environment:
  #     - REDIS_HOSTS=local:redis:6379
  #     - HTTP_USER=root
  #     - HTTP_PASSWORD=qwerty
  #   ports:
  #     - 8081:8081
  #   depends_on:
  #     - redis

  # volumes:
  #   minio:
  #     driver: local
