name: Docker

on:
  # push:
  #   branches: [develop]
  workflow_dispatch:

jobs:
  image:
    name: Build ${{ matrix.component }} Image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        component: [ui, server]
        include:
          - component: ui
            context: ./ui
            dockerfile: ui/Dockerfile
          - component: server
            context: .
            dockerfile: server/Dockerfile
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: arm64
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.context }}
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64
          # platforms: linux/amd64,linux/arm64
          file: ${{ matrix.dockerfile }}
          tags: |
            ghcr.io/nmp-daq-g1/nmp-wt-${{ matrix.component }}:${{ github.sha }}
            ghcr.io/nmp-daq-g1/nmp-wt-${{ matrix.component }}:latest
          labels: ${{ steps.meta.outputs.labels }}
